"use client";
import localFont from "next/font/local";
import "./globals.css";
import { Barlow } from "next/font/google";
import Context from "@/context/context";
import Navbar from "@/components/ui/Navbar";
import { ProductProvider } from "@/context/ProductsContext";
import { CartProvider } from "@/context/CartContext";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const barlow = Barlow({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/*  ${geistSans.variable} ${geistMono.variable} font remove */}
      <body className={` ${barlow.className} antialiased`}>
        <AuthProvider>
          <ProductProvider>
            <CartProvider>{children}</CartProvider>
          </ProductProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
